version: 0.2
env:
  variables:
    PORT: 80
    REPOSITORY_URI: "537678174298.dkr.ecr.us-east-1.amazonaws.com/web"

phases:
  pre_build:
    commonds:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 537678174298.dkr.ecr.us-east-1.amazonaws.com

  build:  
    commands:
      - echo Build started on `date`
      - echo building the docker image...
      - docker build -t $REPOSITORY_URI .

  post_build:
    commands:
      - echo build completed on `date`
      - echo Pushing the docker image...
      - docker push $REPOSITORY_URI:latest
      - aws ecs update-service --cluster web-cluster --service web --force-new-deployment
